### ISSUE TITLE
Gradle wrapper download character issue bin->bın

### ISSUE THREAD

**Issue by fatihpense** [eclipse/buildship#418]
Hi everyone, the plugin tries to download "gradle-3.4-bın.zip" not "bin.zip" 
It may be related to Turkish character problems.

```
Loading Gradle project preview failed due to an error connecting to the Gradle build.
Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-3.4-bın.zip'.

Server returned HTTP response code: 400 for URL: https://downloads.gradle.org/distributions/gradle-3.4-b%fdn.zip
org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-3.4-bın.zip'.
	at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution$1.call(DistributionFactory.java:145)
	at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution$1.call(DistributionFactory.java:133)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultModelBuilder.get(DefaultModelBuilder.java:50)
	at com.gradleware.tooling.toolingclient.internal.DefaultToolingClient.executeAndWait(DefaultToolingClient.java:88)
	at com.gradleware.tooling.toolingclient.internal.DefaultModelRequest.executeAndWait(DefaultModelRequest.java:79)
	at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository$13.get(DefaultModelRepository.java:287)
	at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository.executeAndWait(DefaultModelRepository.java:355)
	at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository.access$100(DefaultModelRepository.java:49)
	at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository$14.call(DefaultModelRepository.java:313)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4724)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4721)
	at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository.getFromCache(DefaultModelRepository.java:330)
	at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository.executeRequest(DefaultModelRepository.java:309)
	at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository.executeRequest(DefaultModelRepository.java:280)
	at com.gradleware.tooling.toolingmodel.repository.internal.DefaultModelRepository.fetchBuildEnvironment(DefaultModelRepository.java:113)
	at org.eclipse.buildship.core.workspace.internal.DefaultModelProvider.fetchBuildEnvironment(DefaultModelProvider.java:51)
	at org.eclipse.buildship.core.projectimport.ProjectPreviewJob.fetchBuildEnvironment(ProjectPreviewJob.java:81)
	at org.eclipse.buildship.core.projectimport.ProjectPreviewJob.runToolingApiJobInWorkspace(ProjectPreviewJob.java:74)
	at org.eclipse.buildship.core.util.progress.ToolingApiWorkspaceJob$1.run(ToolingApiWorkspaceJob.java:79)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
	at org.eclipse.buildship.core.util.progress.ToolingApiWorkspaceJob.runInWorkspace(ToolingApiWorkspaceJob.java:76)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://downloads.gradle.org/distributions/gradle-3.4-b%fdn.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:60)
	at org.gradle.wrapper.Download.download(Download.java:45)
	at org.gradle.tooling.internal.consumer.DistributionFactory$ProgressReportingDownload.download(DistributionFactory.java:202)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution$1.call(DistributionFactory.java:139)
	at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution$1.call(DistributionFactory.java:133)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


```

**Comment by oehme** [comment]
Could you provide a reproducible example project?

**Comment by fatihpense** [comment]
Actually this was a new project in a new workspace (Eclipse Neon). OS is Windows 10 Turkish. 
New Gradle Project "Options" step:
I solved the issue by downloading gradle myself and using local installation directory in this step.

Do you need any additional information?

**Comment by oehme** [comment]
I see, thanks for the clarification!

Sounds like we have a `toLowerCase()` somewhere in the code base which uses the default locale. We should be using `toLowerCase(Locale.English)` instead. @donat I suspect this is either somewhere in Buildship, Tooling Commons or in the toolingApi project.

**Comment by donat** [comment]
@fatihpense It seems that you have hit a [bug in Gradle that was fixed for the upcoming 3.5 release](https://github.com/gradle/gradle/pull/1408). Can you please try if your project works with Gradle 3.5-rc-3?

**Comment by donat** [comment]
I'm going to close the issue. Feel free to reopen if you have further comments.

**Comment by fatihpense** [comment]
OK. There is no update in Eclipse Marketplace so the problem persist for me. I will test it again when there is an update.

**Comment by fatihpense** [comment]
Issue is resolved, thanks!
<img width="328" alt="gradle_wrapper_issue_resolved_2017_04_27" src="https://cloud.githubusercontent.com/assets/918653/25486519/2008b2ba-2b6a-11e7-8350-53f786b577a6.png">

**Comment by donat** [comment]
Excellent, thanks for the feedback!
