### ISSUE TITLE
Dark Theme: fix Window > Preferences > Gradle > Advanced Options background color

### ISSUE THREAD

**Issue by eric-milles** [eclipse/buildship#858]
The "Advanced Options" group control has a background color set that is incompatible with the Dark Theme.

![image](https://user-images.githubusercontent.com/18193802/53753572-3142c300-3e77-11e9-9d98-0c0b16051269.png)

**Comment by donat** [comment]
I thought we fixed this. Do you use the latest version?

**Comment by eric-milles** [comment]
Still appears this way in 3.0.1.v20181217-1554.  This is what update site for Eclipse 4.10 provides.

**Comment by donat** [comment]
Strange. I'll take a look.

**Comment by donat** [comment]
@eric-milles On osx it seemed fine, at least for the first glance:

<img width="738" alt="Screenshot 2019-03-19 at 13 52 34" src="https://user-images.githubusercontent.com/419883/54607399-87eef600-4a4e-11e9-848d-84a1c583dcec.png">

I've just noticed that the `Advanced Options` label has the wrong color. My guess is that this is the bug. I'll provide a patch soon.
